import * as fs from 'node:fs/promises';
import * as path from 'node:path';

import { Logger } from '@nestjs/common';

import { LoggerContextEnum } from '../common/models';

async function createI18nTypesFile(): Promise<void> {
  const pathToFile = path.join(
    process.cwd(),
    'src',
    'common',
    'http',
    'i18n',
    'i18n.generated.ts',
  );
  try {
    await fs.readFile(pathToFile);
    Logger.log('Types already exist', LoggerContextEnum.i18nSyncFiles);
  } catch (err) {
    await fs.writeFile(
      pathToFile,
      '/* DO NOT EDIT, file generated by nestjs-i18n */\n \n' +
        "import { Path } from 'nestjs-i18n';\n \n" +
        'export type I18nTranslations = {}; \n' +
        'export type I18nPath = Path< I18nTranslations >;',
    );
    Logger.log('Types file was created', LoggerContextEnum.i18nSyncFiles);
  }
}

void createI18nTypesFile();
