/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "errors": {
        "TypeOrmUpdatedPatch": string;
    };
    "exceptions": {
        "FilesNotExist": string;
        "NoPermission": string;
        "EntityNotFound": string;
        "Conflict": string;
        "AccessTokenExpired": string;
        "RefreshTokenExpired": string;
        "InvalidCredentials": string;
        "InvalidToken": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
